config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'restaurants#index'

  resources :restaurants do
  resources :reviews
  end
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base

validates :name, presence: true, format: {with: /\A[A-Z]/, message: 'must begin with a capital'}
validates :address, presence: true
validates :cuisine, presence: true

has_many :reviews


	def average_rating
		if reviews.any?
			reviews.average(:rating)
			# reviews.inject(0) {|total, review|
			# total + review.rating
			# } / reviews.count.to_f
		else
		'N/A'
	  end
	end
end

app/models/review.rb
class Review < ActiveRecord::Base

	belongs_to :restaurant
	validates :rating, inclusion: { in: 1..5 }

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

	# removes the need to have authenticate user before every every action
	# before_action: authenticate_user!, except: [:index]

	def index
		@restaurants = Restaurant.all
		@review = Review.new
	end

	def new
		# authenticate_user!
		@restaurant = Restaurant.new
	end

	def create
		# authenticate_user!
		@restaurant = Restaurant.new(params['restaurant'].permit(:name, :address, :cuisine))
		if @restaurant.save
			redirect_to '/restaurants'
		else
			render 'new'
		end
	end

	def edit
		# authenticate_user!
		@restaurant = Restaurant.find(params[:id])
	end

	def update
		# authenticate_user!
		@restaurant = Restaurant.find(params[:id])

		if @restaurant.update(params['restaurant'].permit(:name, :address, :cuisine))
			redirect_to '/restaurants'
		else
			render 'new'
		end
	end

	def destroy
		# authenticate_user!
		@restaurant = Restaurant.find(params[:id])
		@restaurant.delete
		flash[:notice] = "Restaurant DESTROYED"
		redirect_to '/restaurants'
	end


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
  	@restaurant = Restaurant.find (params[:restaurant_id])
  	@review = Review.new
  end

  def create
	@restaurant = Restaurant.find (params[:restaurant_id])
	@review = @restaurant.reviews.create!(params[:review].permit(:thoughts, :rating))
	render 'create', content_type: :json
  	# render json: review.to_json(except: [:id], include: :restaurant)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper

	def star_rating(number)

		return number unless number.respond_to?(:round)
		rounded = number.round
		filled_stars = '★' * rounded 
		empty_stars = '☆' * (5 - rounded) 
		filled_stars + empty_stars

		# ★★★★★
	end


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Yelpmarch</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= notice %> 
<%= alert %>

<% if user_signed_in? %>
  
  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %> 
  <%= link_to('Edit registration', edit_user_registration_path) %>

<% else %>

  <%= link_to('Login', new_user_session_path)  %>
  <%= link_to('Register', new_user_registration_path)  %>
  
<% end %>

<%= yield %>

</body>
</html>

app/views/restaurants/_form.html.erb
<% if @restaurant.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this post from being saved:</h2>
 
    <ul>
    <% @restaurant.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @restaurant do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name, required: true%>

	<%= f.label :address %>
	<%= f.text_field :address, required: true %>

	<%= f.label :cuisine %>
	<%= f.text_field :cuisine, required: true %>

	<%= f.submit %>

<% end %>

app/views/restaurants/edit.html.erb
<%= render "form" %>

app/views/restaurants/index.html.erb
<template id='review_template'>
<li>
 <strong> {{ star_rating }} </strong> {{ thoughts }}
 </li>
</template>


<% if @restaurants.any? %>

 <% @restaurants.each do |restaurant| %>
 <div class='restaurant'> 
  	<h2> <%= restaurant.name %> </h2>
  	<% if user_signed_in? %>
  	 <%= link_to "Edit #{restaurant.name}", edit_restaurant_path(restaurant) %>
  	 <%= link_to "Delete #{restaurant.name}", restaurant_path(restaurant), method: :delete %>
  	 <%= link_to "Review #{restaurant.name}", new_restaurant_review_path(restaurant) %>
  	<%end%>
	<h4 class='review_count'><%= pluralize restaurant.reviews.count, 'reviews' %></h4>
	<h5>Average rating: 
    <span class='average_rating_number'>
	  <%= number_with_precision(restaurant.average_rating, precision: 1) %>
	  </span>
    <span class='average_rating_stars'>
    <%= star_rating(restaurant.average_rating) %>
    </span>
  </h5>
 	<ul>
	    <% restaurant.reviews.each do |review| %>
	 	<li>
	 	  <strong><%= star_rating review.rating %></strong> - <%= review.thoughts %>
	 	</li>
     <% end %>
  </ul>	


    <% if user_signed_in? %>
    <%= form_for [restaurant, @review] do |f| %>

       <%= f.label :thoughts %>
       <%= f.text_area :thoughts %>

       <%= f.label :rating %>
       <%= f.select :rating, 1..5 %>

       <%= f.submit 'Leave Review' %>
      <%end%>

   <% end %>
   </div>
  <%end%>
<%else%>

 No restaurants yet

<% end %>

 <%= link_to "Create a restaurant", new_restaurant_path %>

app/views/restaurants/new.html.erb
<%= render "form" %>

app/views/reviews/new.html.erb
<%= form_for [@restaurant, @review] do |f| %>

<%= f.label :thoughts %>
<%= f.text_area :thoughts %>

<%= f.label :rating %>
<%= f.select :rating, 1..5 %>

<%= f.submit 'Leave Review' %>

<% end %>